language: node_js
node_js:
  - '8'
branchs:
  only:
  - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run lint
  - npm run unit
  - npm run e2e
  - npm run serve
  - npm run serve -p
  - npm run build
