language: node_js
node_js:
  - '10'
branchs:
  only:
  - master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run lint
  - npm run unit:c
  - npm run build
